apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bifromq.fullname" . }}-config
  labels:
    {{- include "bifromq.labels" . | nindent 4 }}
data:
  standalone.yml: |
    {{- if .Values.plugin.authProviderFQN }}
    authProviderFQN: {{ .Values.plugin.authProviderFQN | quote }}
    {{- end }}
    {{- if .Values.plugin.resourceThrottlerFQN }}
    resourceThrottlerFQN: {{ .Values.plugin.resourceThrottlerFQN | quote }}
    {{- end }}
    {{- if .Values.plugin.settingProviderFQN }}
    settingProviderFQN: {{ .Values.plugin.settingProviderFQN | quote }}
    {{- end }}

    mqttServiceConfig:
      server:
        tcpListener:
          port: {{ .Values.mqtt.tcpPort }}
        {{- if .Values.mqtt.tlsEnabled }}
        tlsListener:
          enable: true
          port: {{ .Values.mqtt.tlsPort }}
          {{- if .Values.tls.certSecretName }}
          sslConfig:
            certFile: "{{ .Values.tls.mountPath }}/{{ .Values.tls.certFile }}"
            keyFile: "{{ .Values.tls.mountPath }}/{{ .Values.tls.keyFile }}"
            trustCertsFile: "{{ .Values.tls.mountPath }}/{{ .Values.tls.trustCertsFile }}"
            clientAuth: {{ .Values.tls.clientAuth }}
          {{- end }}
        {{- end }}
        {{- if .Values.mqtt.wsEnabled }}
        wsListener:
          enable: true
          port: {{ .Values.mqtt.wsPort }}
          wsPath: {{ .Values.mqtt.wsPath | quote }}
        {{- end }}

    {{- if .Values.apiServer.enabled }}
    apiServerConfig:
      enable: true
      httpPort: {{ .Values.apiServer.port }}
    {{- end }}

    clusterConfig:
      env: {{ .Values.clusterConfig.env | quote }}
      port: {{ .Values.clusterConfig.port }}
      clusterDomainName: {{ include "bifromq.headlessServiceFQDN" . | quote }}

    distServiceConfig:
      worker:
        walEngineConfig:
          groupCommit: {{ .Values.engineConfig.groupCommit }}

    inboxServiceConfig:
      store:
        walEngineConfig:
          groupCommit: {{ .Values.engineConfig.groupCommit }}

    retainServiceConfig:
      store:
        walEngineConfig:
          groupCommit: {{ .Values.engineConfig.groupCommit }}
