apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bifromq-metrics
  namespace: bifromq
  labels:
    app: bifromq
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bifromq
      app.kubernetes.io/instance: bifromq
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - bifromq
