apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bifromq.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bifromq.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "bifromq.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
