apiVersion: v1
kind: Service
metadata:
  name: bifromq
  namespace: bifromq
  labels:
    app: bifromq
spec:
  type: NodePort
  selector:
    app: bifromq
  ports:
    - name: mqtt-tcp
      port: 1883
      targetPort: 1883
      nodePort: 31883
      protocol: TCP
    - name: mqtt-quic
      port: 1884
      targetPort: 1884
      nodePort: 31884
      protocol: UDP
    - name: admin
      port: 8080
      targetPort: 8080
      nodePort: 31880
      protocol: TCP
    - name: cluster-gossip
      port: 14567
      targetPort: 14567
      nodePort: 31456
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: bifromq-headless
  namespace: bifromq
  labels:
    app: bifromq
spec:
  clusterIP: None
  selector:
    app: bifromq
  ports:
    - name: mqtt-tcp
      port: 1883
      protocol: TCP
    - name: mqtt-quic
      port: 1884
      protocol: UDP
    - name: admin
      port: 8080
      protocol: TCP
    - name: cluster-gossip
      port: 14567
      protocol: UDP
